image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: dev
  CI_REGISTRY_IMAGE: registry-sqm.qligent.com/qligent_sqm/frontend
  TRIGGER_TOKEN: de12987e78b73d33c19149a831e448

node-build:
  image: node:8.9.4 
  only:
  - web
  stage: build
  script:
  - apt-get update
  - apt-get install -y libpng-dev
  - mkdir ./build
  - chmod 777 ./build
  - npm install
  - npm run build
  - ls -la ./build
  cache:
    key: js_html_css
    paths:
    - build
    policy: push

docker-package:
  image: docker:latest
  only:
  - web
  stage: package
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $dockerRegistryHost
  - export FRONTEND_VERSION=$(cat ./package.json | grep version | sed 's/.*\([0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}.*\)",/\1/')
  - ls -la ./build
  - docker build -t $CI_REGISTRY_IMAGE:$FRONTEND_VERSION .
  - docker push $CI_REGISTRY_IMAGE
  cache:
    key: js_html_css
    paths:
    - build
    policy: pull
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
    
trigger_build:
  image: centos
  only:
  - web
  stage: deploy
  script:
    - "curl -X POST -F token=${TRIGGER_TOKEN} -F ref=develop http://gitlab-sqm.qligent.com/api/v4/projects/8/trigger/pipeline"

