image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: dev

node-build:
  image: node:8.9.4 
  only:
  - web
  stage: build
  script:
  - apt-get update
  - apt-get install -y libpng-dev
  - npm install
  - npm run build
  - ls -la ./build
  cache:
    key: js_html_css
    paths:
    - build
    policy: push

docker-package:
  image: docker:latest
  only:
  - web
  stage: package
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $dockerRegistryHost
  - export FRONTEND_VERSION=$(cat ./package.json | grep version | sed 's/.*\([0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}.*\)",/\1/')
  - ls -la ./build
  - docker build -t $CI_REGISTRY_IMAGE:$FRONTEND_VERSION .
  - docker push $CI_REGISTRY_IMAGE
  cache:
    key: js_html_css
    paths:
    - build
    policy: pull
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
